language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy2.7"
  - "pypy3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
virtualenv:
  system_site_packages: true
